apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 30s
    spec:
      containers:
        - image: docker.io/kiemtcb/detection-object:4.0arm@sha256:2aee3da31b2e4d077eb9b1059cdcd9051f572ef9baa083865585a1eb48836438
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: jetson