apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 30s
    spec:
      containers:
        - image: docker.io/kiemtcb/detection-object:4.3arm@sha256:455079bdc7541900802afe0e062d2f4b8733dc8dfe1c25e6b31efb9d73ce9533
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: jetson