apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 6s
    spec:
      containers:
      - image: docker.io/kiemtcb/detection-object:4.2arm@sha256:9161d9188d1c196ade0e3555a2618bee41cfae9ac713a62e7b6c8419bb59e081
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: jetson
