apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 30s
    spec:
      containers:
        - image: docker.io/kiemtcb/detection-object:4.1x86@sha256:d9fd9c86eae98793d174bc3791708472d312523d7de5da1631c709a157d248a2
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: mec