apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 30s
    spec:
      containers:
        - image: docker.io/kiemtcb/detection-object:2.0x86@sha256:65629bc66af81e77315094d8a576cdede9ff8e8fa9d30a2183f9e631cc5e9d17
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: mec